import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class MaterialsService {

  materials = [
    {"value": "ACEITE DW 40", "viewValue": "ACEITE DW 40"},
    {"value": "ADAPTADORES GALPONERA", "viewValue": "ADAPTADORES GALPONERA"},
    {"value": "ARANDELAS", "viewValue": "ARANDELAS"},
    {"value": "BALASTRO EXTERIOR 150W", "viewValue": "BALASTRO EXTERIOR 150W"},
    {"value": "BALASTRO EXTERIOR 250W", "viewValue": "BALASTRO EXTERIOR 250W"},
    {"value": "BALASTRO EXTERIOR 400W", "viewValue": "BALASTRO EXTERIOR 400W"},
    {"value": "BALASTRO INTERIOR 100W", "viewValue": "BALASTRO INTERIOR 100W"},
    {"value": "BALASTRO INTERIOR 150W", "viewValue": "BALASTRO INTERIOR 150W"},
    {"value": "BALASTRO INTERIOR 250W", "viewValue": "BALASTRO INTERIOR 250W"},
    {"value": "BANDEJA BALASTO 70W CON IGNITOR", "viewValue": "BANDEJA BALASTO 70W CON IGNITOR"},
    {"value": "BASE PORTA FUSIBLE", "viewValue": "BASE PORTA FUSIBLE"},
    {"value": "BORNERA", "viewValue": "BORNERA"},
    {"value": "BORNERA 100A", "viewValue": "BORNERA 100A"},
    {"value": "BORNERA 16A", "viewValue": "BORNERA 16A"},
    {"value": "BORNERA 200A", "viewValue": "BORNERA 200A"},
    {"value": "BORNERA 25A", "viewValue": "BORNERA 25A"},
    {"value": "BORNERA 60A", "viewValue": "BORNERA 60A"},
    {"value": "BRAZO CORTO VEREDA ( codo a 45 )", "viewValue": "BRAZO CORTO VEREDA ( codo a 45 )"},
    {"value": "BRAZO CORTO VEREDA ( codo a 90 )", "viewValue": "BRAZO CORTO VEREDA ( codo a 90 )"},
    {"value": "CABLE PROTO 3X4 MM", "viewValue": "CABLE PROTO 3X4 MM"},
    {"value": "CABLE VAINA CHATA X M", "viewValue": "CABLE VAINA CHATA X M"},
    {"value": "CALLARINES DE 50 GRADOS", "viewValue": "CALLARINES DE 50 GRADOS"},
    {"value": "CANDADO 40", "viewValue": "CANDADO 40"},
    {"value": "CAPUCHONES", "viewValue": "CAPUCHONES"},
    {"value": "CINTA AISLADORA", "viewValue": "CINTA AISLADORA"},
    {"value": "CINTA ANCHA", "viewValue": "CINTA ANCHA"},
    {"value": "CINTA AUTOSOLDABLE", "viewValue": "CINTA AUTOSOLDABLE"},
    {"value": "CINTA PAPEL", "viewValue": "CINTA PAPEL"},
    {"value": "CINTA PELIGRO", "viewValue": "CINTA PELIGRO"},
    {"value": "CLAVOS X KG", "viewValue": "CLAVOS X KG"},
    {"value": "COLLARINES 110 GRADOS", "viewValue": "COLLARINES 110 GRADOS"},
    {"value": "COLLARINES 30 GRADOS", "viewValue": "COLLARINES 30 GRADOS"},
    {"value": "COLLARINES 65 GRADOS", "viewValue": "COLLARINES 65 GRADOS"},
    {"value": "COLLARINES 90 GRADOS", "viewValue": "COLLARINES 90 GRADOS"},
    {"value": "COLLARINES 90 GRADOS", "viewValue": "COLLARINES 90 GRADOS"},
    {"value": "DICROICA 7W", "viewValue": "DICROICA 7W"},
    {"value": "DISCO DE CORTE", "viewValue": "DISCO DE CORTE"},
    {"value": "DRIVER 150", "viewValue": "DRIVER 150"},
    {"value": "EQUIPO ATRIA LED", "viewValue": "EQUIPO ATRIA LED"},
    {"value": "EQUIPO ATRIA SODIO", "viewValue": "EQUIPO ATRIA SODIO"},
    {"value": "EQUIPO ATRIA SODIO", "viewValue": "EQUIPO ATRIA SODIO"},
    {"value": "EQUIPO GEA32", "viewValue": "EQUIPO GEA32"},
    {"value": "EQUIPO GEACI32", "viewValue": "EQUIPO GEACI32"},
    {"value": "EQUIPO GEAPI32", "viewValue": "EQUIPO GEAPI32"},
    {"value": "EQUIPO PI96", "viewValue": "EQUIPO PI96"},
    {"value": "EQUIPO TRIVIALTECH", "viewValue": "EQUIPO TRIVIALTECH"},
    {"value": "EQUIPO TRIVIALTECH", "viewValue": "EQUIPO TRIVIALTECH"},
    {"value": "EQUIPO VC120", "viewValue": "EQUIPO VC120"},
    {"value": "EQUIPO VC32", "viewValue": "EQUIPO VC32"},
    {"value": "EQUIPO VC48", "viewValue": "EQUIPO VC48"},
    {"value": "EQUIPO VC64", "viewValue": "EQUIPO VC64"},
    {"value": "EQUIPO VC84", "viewValue": "EQUIPO VC84"},
    {"value": "EQUIPO VC96", "viewValue": "EQUIPO VC96"},
    {"value": "FISUBLE 250", "viewValue": "FISUBLE 250"},
    {"value": "FOTOCELULA", "viewValue": "FOTOCELULA"},
    {"value": "FUSIBLE 10X38 10A", "viewValue": "FUSIBLE 10X38 10A"},
    {"value": "FUSIBLE 10X38 4A", "viewValue": "FUSIBLE 10X38 4A"},
    {"value": "FUSIBLE 10X38 6A", "viewValue": "FUSIBLE 10X38 6A"},
    {"value": "FUSIBLE CERAMICA", "viewValue": "FUSIBLE CERAMICA"},
    {"value": "FUSIBLE NH 100", "viewValue": "FUSIBLE NH 100"},
    {"value": "FUSIBLE NH 125", "viewValue": "FUSIBLE NH 125"},
    {"value": "FUSIBLE NH 50", "viewValue": "FUSIBLE NH 50"},
    {"value": "FUSIBLE NH 63", "viewValue": "FUSIBLE NH 63"},
    {"value": "FUSIBLE NH 80 A", "viewValue": "FUSIBLE NH 80 A"},
    {"value": "FUSIBLE NH80A", "viewValue": "FUSIBLE NH80A"},
    {"value": "GABINETES", "viewValue": "GABINETES"},
    {"value": "GALPONERA 40W", "viewValue": "GALPONERA 40W"},
    {"value": "GALPONERA 50W", "viewValue": "GALPONERA 50W"},
    {"value": "GAS BUTANO", "viewValue": "GAS BUTANO"},
    {"value": "GUANTES MOTEADOS", "viewValue": "GUANTES MOTEADOS"},
    {"value": "GUANTES VAQUETA", "viewValue": "GUANTES VAQUETA"},
    {"value": "IGNITORES", "viewValue": "IGNITORES"},
    {"value": "JABALINAS", "viewValue": "JABALINAS"},
    {"value": "KIT DE EMPALME 10 A 35MM", "viewValue": "KIT DE EMPALME 10 A 35MM"},
    {"value": "KIT DE EMPALME RAPIDO", "viewValue": "KIT DE EMPALME RAPIDO"},
    {"value": "LAMPARA AR111 FRIA", "viewValue": "LAMPARA AR111 FRIA"},
    {"value": "LAMPARA COMUN", "viewValue": "LAMPARA COMUN"},
    {"value": "LAMPARA ROSEDAL", "viewValue": "LAMPARA ROSEDAL"},
    {"value": "LAMPARA SODIO 100W", "viewValue": "LAMPARA SODIO 100W"},
    {"value": "LAMPARA SODIO 150W", "viewValue": "LAMPARA SODIO 150W"},
    {"value": "LAMPARA SODIO 250W", "viewValue": "LAMPARA SODIO 250W"},
    {"value": "LAMPARA SODIO 400W", "viewValue": "LAMPARA SODIO 400W"},
    {"value": "MANGUITO DE EMPALME 10 MM", "viewValue": "MANGUITO DE EMPALME 10 MM"},
    {"value": "MANGUITO DE EMPALME 16 MM", "viewValue": "MANGUITO DE EMPALME 16 MM"},
    {"value": "MANGUITO DE EMPALME 25 MM", "viewValue": "MANGUITO DE EMPALME 25 MM"},
    {"value": "MANGUITO DE EMPALME 35 MM", "viewValue": "MANGUITO DE EMPALME 35 MM"},
    {"value": "MANGUITO DE EMPALME 6 MM", "viewValue": "MANGUITO DE EMPALME 6 MM"},
    {"value": "MORSETO PKD14", "viewValue": "MORSETO PKD14"},
    {"value": "MORSETO PKD16", "viewValue": "MORSETO PKD16"},
    {"value": "MORSETOS PK20", "viewValue": "MORSETOS PK20"},
    {"value": "NH 25A NT000", "viewValue": "NH 25A NT000"},
    {"value": "NH 36A NT000", "viewValue": "NH 36A NT000"},
    {"value": "NH100 NT1", "viewValue": "NH100 NT1"},
    {"value": "NH160A NT000", "viewValue": "NH160A NT000"},
    {"value": "NH160A NT1", "viewValue": "NH160A NT1"},
    {"value": "NH200 NT1", "viewValue": "NH200 NT1"},
    {"value": "NH400 NH2", "viewValue": "NH400 NH2"},
    {"value": "NH63 NH1", "viewValue": "NH63 NH1"},
    {"value": "NUQUERA", "viewValue": "NUQUERA"},
    {"value": "PILAS", "viewValue": "PILAS"},
    {"value": "PINZA RETENCION CHICA", "viewValue": "PINZA RETENCION CHICA"},
    {"value": "PINZA RETENCION GRANDE", "viewValue": "PINZA RETENCION GRANDE"},
    {"value": "PORTA LAMPARAS E27", "viewValue": "PORTA LAMPARAS E27"},
    {"value": "PORTA LAMPARAS E40", "viewValue": "PORTA LAMPARAS E40"},
    {"value": "PRECINTOS", "viewValue": "PRECINTOS"},
    {"value": "PRECINTOS DE 150X3.6", "viewValue": "PRECINTOS DE 150X3.6"},
    {"value": "PRECINTOS DE 20 CM", "viewValue": "PRECINTOS DE 20 CM"},
    {"value": "PRECINTOS DE 250X3.6", "viewValue": "PRECINTOS DE 250X3.6"},
    {"value": "PROTECTOR SOBRETENSION 10 KA", "viewValue": "PROTECTOR SOBRETENSION 10 KA"},
    {"value": "REFLECTOR 10W FRIO", "viewValue": "REFLECTOR 10W FRIO"},
    {"value": "REFLECTOR 70 W", "viewValue": "REFLECTOR 70 W"},
    {"value": "REFLECTOR LED 100W CALIDO", "viewValue": "REFLECTOR LED 100W CALIDO"},
    {"value": "REFLECTOR LED 100W FRIA", "viewValue": "REFLECTOR LED 100W FRIA"},
    {"value": "REFLECTOR LED 100W FRIA C/ COBERTOR", "viewValue": "REFLECTOR LED 100W FRIA C/ COBERTOR"},
    {"value": "REFLECTOR LED 150W FRIA", "viewValue": "REFLECTOR LED 150W FRIA"},
    {"value": "REFLECTOR LED 200W FRIA", "viewValue": "REFLECTOR LED 200W FRIA"},
    {"value": "REFLECTOR LED 50W", "viewValue": "REFLECTOR LED 50W"},
    {"value": "REFLECTOR RGB 50W", "viewValue": "REFLECTOR RGB 50W"},
    {"value": "RIELDIN", "viewValue": "RIELDIN"},
    {"value": "ROLLO DE ALAMBRE", "viewValue": "ROLLO DE ALAMBRE"},
    {"value": "SILICONA FASTIX", "viewValue": "SILICONA FASTIX"},
    {"value": "SUSPENCIONES", "viewValue": "SUSPENCIONES"},
    {"value": "TABAQUERA", "viewValue": "TABAQUERA"},
    {"value": "TACO FISCHER N 8", "viewValue": "TACO FISCHER N 8"},
    {"value": "TAPAS CHICAS", "viewValue": "TAPAS CHICAS"},
    {"value": "TAPAS GRANDES", "viewValue": "TAPAS GRANDES"},
    {"value": "TAPAS MEDIANAS", "viewValue": "TAPAS MEDIANAS"},
    {"value": "TERMICA UNIPOLAR 6A", "viewValue": "TERMICA UNIPOLAR 6A"},
    {"value": "TERMINAL DE OJAL CHICO 10 MM", "viewValue": "TERMINAL DE OJAL CHICO 10 MM"},
    {"value": "TERMINAL DE OJAL CHICO 16 MM", "viewValue": "TERMINAL DE OJAL CHICO 16 MM"},
    {"value": "TERMINAL DE OJAL CHICO 2,5 MM", "viewValue": "TERMINAL DE OJAL CHICO 2,5 MM"},
    {"value": "TERMINAL DE OJAL CHICO 25 MM", "viewValue": "TERMINAL DE OJAL CHICO 25 MM"},
    {"value": "TERMINAL DE OJAL CHICO 4 MM", "viewValue": "TERMINAL DE OJAL CHICO 4 MM"},
    {"value": "TERMINAL DE OJAL CHICO 6 MM", "viewValue": "TERMINAL DE OJAL CHICO 6 MM"},
    {"value": "TERMINAL OJAN GRANDE 10 MM", "viewValue": "TERMINAL OJAN GRANDE 10 MM"},
    {"value": "TERMINAL OJAN GRANDE 16 MM", "viewValue": "TERMINAL OJAN GRANDE 16 MM"},
    {"value": "TERMINAL OJAN GRANDE 2,5 MM", "viewValue": "TERMINAL OJAN GRANDE 2,5 MM"},
    {"value": "TERMINAL OJAN GRANDE 25 MM", "viewValue": "TERMINAL OJAN GRANDE 25 MM"},
    {"value": "TERMINAL OJAN GRANDE 4 MM", "viewValue": "TERMINAL OJAN GRANDE 4 MM"},
    {"value": "TERMINAL OJAN GRANDE 6 MM", "viewValue": "TERMINAL OJAN GRANDE 6 MM"},
    {"value": "TERMINALES DE PUNTA 1.5", "viewValue": "TERMINALES DE PUNTA 1.5"},
    {"value": "TERMINALES DE PUNTA 10", "viewValue": "TERMINALES DE PUNTA 10"},
    {"value": "TERMINALES DE PUNTA 16", "viewValue": "TERMINALES DE PUNTA 16"},
    {"value": "TERMINALES DE PUNTA 2.5", "viewValue": "TERMINALES DE PUNTA 2.5"},
    {"value": "TERMINALES DE PUNTA 4", "viewValue": "TERMINALES DE PUNTA 4"},
    {"value": "TERMINALES DE PUNTA 6", "viewValue": "TERMINALES DE PUNTA 6"},
    {"value": "TERMINALES OJAL 185MM", "viewValue": "TERMINALES OJAL 185MM"},
    {"value": "TERMINALES OJAL 95MM", "viewValue": "TERMINALES OJAL 95MM"},
    {"value": "TERMOCONTRAIBLE DE 12-7MM (1/2)", "viewValue": "TERMOCONTRAIBLE DE 12-7MM (1/2)"},
    {"value": "TERMOCONTRAIBLE DE 4.8MM ( 3/16)", "viewValue": "TERMOCONTRAIBLE DE 4.8MM ( 3/16)"},
    {"value": "TERMOCONTRIBLE DE 6.4MM (1/4)", "viewValue": "TERMOCONTRIBLE DE 6.4MM (1/4)"},
    {"value": "TIMER ANALOGICO", "viewValue": "TIMER ANALOGICO"},
    {"value": "TIMER DIGITAL", "viewValue": "TIMER DIGITAL"},
    {"value": "TORNILLO AUTOPERFORANTES CHICOS CABEZA PHILLIPS", "viewValue": "TORNILLO AUTOPERFORANTES CHICOS CABEZA PHILLIPS"},
    {"value": "TORNILLO AUTOPERFORANTES CHICOS PARA MECHA COPA", "viewValue": "TORNILLO AUTOPERFORANTES CHICOS PARA MECHA COPA"},
    {"value": "TORNILLO AUTOPERFORANTES MEDIANOS C/GOMITA MECHA COPA", "viewValue": "TORNILLO AUTOPERFORANTES MEDIANOS C/GOMITA MECHA COPA"},
    {"value": "TORNILLO AUTOPERFORANTES MEDIANOS CABEZA PHILLIPS", "viewValue": "TORNILLO AUTOPERFORANTES MEDIANOS CABEZA PHILLIPS"},
    {"value": "TORNILLO AUTOPERFORANTES MEDIANOS PARA MECHA COPA", "viewValue": "TORNILLO AUTOPERFORANTES MEDIANOS PARA MECHA COPA"},
    {"value": "TORNILLO CABEZA HEXAGONAL", "viewValue": "TORNILLO CABEZA HEXAGONAL"},
    {"value": "TORNILLO DEL 6 C/ TACO FISCHER", "viewValue": "TORNILLO DEL 6 C/ TACO FISCHER"},
    {"value": "TORNILLO DEL 8 C/ TACO FISCHER", "viewValue": "TORNILLO DEL 8 C/ TACO FISCHER"},
    {"value": "TORNILLOS AUTOPERFORANTES GRANDES CABEZA PHILLIPS", "viewValue": "TORNILLOS AUTOPERFORANTES GRANDES CABEZA PHILLIPS"},
    {"value": "TORNILLOS AUTOPERFORANTES GRANDES PARA MECHA COPA", "viewValue": "TORNILLOS AUTOPERFORANTES GRANDES PARA MECHA COPA"},
    {"value": "TORNILLOS N 8", "viewValue": "TORNILLOS N 8"},
    {"value": "TORNILLOS SEGURIDAD", "viewValue": "TORNILLOS SEGURIDAD"},
    {"value": "TPR 3X25", "viewValue": "TPR 3X25"},
    {"value": "TUERCAS PARA VARILLA ROSCADA", "viewValue": "TUERCAS PARA VARILLA ROSCADA"},
    {"value": "VARILLA ROSCADA", "viewValue": "VARILLA ROSCADA"},
    {"value": "W40", "viewValue": "W40"},
    {"value": "ZOCALO FOTOCELULA", "viewValue": "ZOCALO FOTOCELULA"}
]


  constructor() { }

  getMaterials(){
    return this.materials;
}
}
